### ISSUE TITLE
Cannot use the package on iOS/Android

### ISSUE THREAD

**Issue by drpiou** [cnjon/react-native-datetime#14]
I just installed this package and I cannot use it at all with this error message:
"Super expression must either be null or a function, not undefined." for both iOS and Android.

I'm running React Native:
react-native-cli: 0.2.0
react-native: 0.26.0

![screenshot_20160523-140257](https://cloud.githubusercontent.com/assets/474368/15470180/4ba248b8-20ef-11e6-86cf-706bb01c0b2e.png)

**Comment by drpiou** [comment]
I resolved this error for Android replacing this:

```
import React,{
    Component,
    NativeModules,
    PropTypes,
    View,
} from 'react-native';
```

by this:

```
import { Component, PropTypes } from 'react';
import React, { NativeModules, View, } from 'react-native';
```

**Comment by cnjon** [comment]
@drpiou Thanks!
I have published!

**Comment by drpiou** [comment]
Your welcome :)
