### ISSUE TITLE
【bug】showDatePicker的date错误

### ISSUE THREAD

**Issue by WhatAKitty** [cnjon/react-native-datetime#7]
this.setState({
    date: new Date()
})
这里应该是传入的date值。
还有想请教下，怎么总是警告提示date必须为Date类型以及onDateChange不可为空的错误，是不是跟我升级到React Native 0.22.2有关？

**Comment by cnjon** [comment]
@WhatAKitty DatePickerIOS一直有这个警告，但不影响使用。
